draft: support merklized credential
0xPolygonID/anon-aadhaar pull request #1
Opened 2024-12-26 10:27 UTC by ilya-korotya

2024-12-26 15:55 UTC, demonsh requested changes
Please add description to the VC templates.  Move it to separate folder. 
+ Instructions how to generate templates and how it works, so developers will understand the algorithm 
+ Move Merklization  to separate Template.
+ Move ClaimRootBuilder to separate file

2024-12-28 01:31 UTC, OBrezhniev requested changes

2024-12-28 01:31 UTC, OBrezhniev commented on packages/circuits/src/aadhaar-qr-verifier.circom
> +    signal input siblings[10][nLevels];
Create a template param with number of smt changes.

2024-12-28 01:31 UTC, OBrezhniev commented on packages/circuits/src/aadhaar-qr-verifier.circom
> +        smt[i].fnc <== [0, 1];
Function value you pass doesn't look correct here.

2024-12-28 01:31 UTC, OBrezhniev commented on packages/circuits/test/aadhaar-verifier.test.ts
> +  const constLefasUpdate = [
Typo

2024-12-28 01:31 UTC, OBrezhniev commented on packages/circuits/test/aadhaar-verifier.test.ts
> +    "4809579517396073186705705159186899409599314609122482090560534255195823961763", "2038038677412689124034084719683107814279606773706261227437666149072023632255",
Can you please add comments here too? What are the first & second values on each line and how have you calculated them.

2024-12-28 01:31 UTC, OBrezhniev commented on packages/circuits/test/aadhaar-verifier.test.ts
> +    credentialStatusID: "1018201307016207665766251269200564043201648522038849723333336008159229499355",
Please add comments on how you got these values.

2024-12-28 01:31 UTC, OBrezhniev commented on packages/circuits/test/aadhaar-verifier.test.ts
> +    assert(witness[3] === BigInt("4230341195722595158824846810955105073061381863438730322129274755644729517884"));
What are you checking here?

2024-12-28 01:31 UTC, OBrezhniev commented on packages/circuits/test/extractor.test.ts
> +    // Data of birth on integer format
Date, not data.
In integer format, not on.

2025-01-07 15:38 UTC, ilya-korotya commented on packages/circuits/src/aadhaar-qr-verifier.circom
> +        smt[i].fnc <== [0, 1];
I pass the update flag as here in the example: https://github.com/iden3/circomlib/blob/master/test/smtprocessor.js#L73

2025-01-07 16:10 UTC, ilya-korotya commented on packages/circuits/src/aadhaar-qr-verifier.circom
> +    signal input siblings[10][nLevels];
done

2025-01-07 16:11 UTC, ilya-korotya commented on packages/circuits/test/aadhaar-verifier.test.ts
> +  const constLefasUpdate = [
done

2025-01-07 16:11 UTC, ilya-korotya commented on packages/circuits/test/aadhaar-verifier.test.ts
> +    "4809579517396073186705705159186899409599314609122482090560534255195823961763", "2038038677412689124034084719683107814279606773706261227437666149072023632255",
done

2025-01-07 16:11 UTC, ilya-korotya commented on packages/circuits/test/aadhaar-verifier.test.ts
> +    assert(witness[3] === BigInt("4230341195722595158824846810955105073061381863438730322129274755644729517884"));
done

2025-01-07 16:11 UTC, ilya-korotya commented on packages/circuits/test/extractor.test.ts
> +    // Data of birth on integer format
done

2025-01-07 16:12 UTC, ilya-korotya commented on packages/circuits/test/aadhaar-verifier.test.ts
> +    credentialStatusID: "1018201307016207665766251269200564043201648522038849723333336008159229499355",
I'm going to create notion page with instructions how to calculate all key-value pairs.

2025-01-13 17:58 UTC, demonsh commented on packages/circuits/src/aadhaar-qr-verifier.circom
> +    var i0 = 11838043422440293315007254764009275008602;
Add set of attributes for the library

2025-04-22 12:53 UTC, ilya-korotya commented
Moved to https://github.com/0xPolygonID/passport-circuits/pull/22

2025-04-22 12:53 UTC, closed without merging